"""
Inference helper for diacritics restoration.

Loads a fine-tuned ByT5 checkpoint and exposes a `restore` method that returns
the restored text, the character positions that changed, an overall confidence
score, AND a per-character confidence array suitable for UI highlighting.

Per-character confidence (project spec §3.3) is extracted from the model's own softmax distributions during
generation. ByT5 emits UTF-8 bytes, so multi-byte Romanian characters span
multiple generation steps; we aggregate by taking the product of byte-level
probabilities (= the joint probability of generating the whole character).
"""

from __future__ import annotations

import logging
import math
from dataclasses import dataclass, asdict
from pathlib import Path

import torch
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer

logger = logging.getLogger(__name__)

# ByT5 vocabulary layout: token IDs 0/1/2 are special (pad, eos, unk),
# IDs 3..258 are the 256 raw bytes (byte_value = token_id - 3),
# IDs 259+ are extra/sentinel tokens we don't expect at inference time.
_BYT5_OFFSET = 3
_BYT5_BYTE_RANGE = range(_BYT5_OFFSET, _BYT5_OFFSET + 256)


@dataclass
class RestorationResult:
    input: str
    restored: str
    changed_positions: list[int]      # indices in 'restored'
    confidence: float                 # overall mean per-token probability, [0, 1]
    char_confidences: list[float]     # per-character probability, len == len(restored)

    def to_dict(self) -> dict:
        return asdict(self)


class DiacriticsRestorer:
    """Wrapper around a fine-tuned ByT5 model for diacritics restoration."""

    def __init__(
        self,
        model_path: str | Path,
        device: str | None = None,
        max_input_length: int = 1024,
        max_output_length: int = 1024,
        num_beams: int = 4,
    ):
        self.model_path = str(model_path)
        self.device = device or ("cuda" if torch.cuda.is_available() else "cpu")
        self.max_input_length = max_input_length
        self.max_output_length = max_output_length
        self.num_beams = num_beams

        logger.info("Loading model from %s on %s", self.model_path, self.device)
        self.tokenizer = AutoTokenizer.from_pretrained(self.model_path)
        self.model = AutoModelForSeq2SeqLM.from_pretrained(self.model_path)
        self.model.to(self.device)
        self.model.eval()

    @torch.no_grad()
    def restore(self, text: str) -> RestorationResult:
        if not text.strip():
            return RestorationResult(
                input=text, restored=text, changed_positions=[],
                confidence=1.0, char_confidences=[1.0] * len(text),
            )

        enc = self.tokenizer(
            text,
            return_tensors="pt",
            truncation=True,
            max_length=self.max_input_length,
        ).to(self.device)

        # We need num_beams=1 for clean per-step probabilities.
        # Beam search returns aggregate sequence_scores but doesn't expose
        # per-step per-beam logits cleanly enough for character-level mapping.
        # Greedy is also faster, and at the per-token-prob level beam search
        # would only differ marginally here anyway since the model is highly
        # confident on most tokens.
        out = self.model.generate(
            **enc,
            max_new_tokens=self.max_output_length,
            num_beams=1,
            do_sample=False,
            return_dict_in_generate=True,
            output_scores=True,
        )

        sequence = out.sequences[0]
        restored, char_probs = self._decode_with_char_probs(sequence, out.scores)
        confidence = (
            float(sum(char_probs) / len(char_probs)) if char_probs else 1.0
        )
        changed_positions = self._diff_positions(text, restored)

        return RestorationResult(
            input=text,
            restored=restored,
            changed_positions=changed_positions,
            confidence=confidence,
            char_confidences=char_probs,
        )

    def restore_batch(self, texts: list[str]) -> list[RestorationResult]:
        """Simple per-item loop; adequate for demo throughput."""
        return [self.restore(t) for t in texts]

    # ------------------------------------------------------------------
    # Per-character confidence: byte-level softmax -> character probs
    # ------------------------------------------------------------------

    def _decode_with_char_probs(
        self,
        sequence: torch.Tensor,
        scores: tuple[torch.Tensor, ...],
    ) -> tuple[str, list[float]]:
        """Decode a generated byte sequence into characters with per-char probs.

        Walks the generated tokens, computes the softmax probability of each
        chosen byte, then groups bytes into UTF-8 characters and aggregates
        their probabilities by taking the product (joint probability of
        emitting all bytes of the character correctly).
        """
        # `sequence` includes the decoder-start token at index 0; per-step
        # `scores[i]` is the logit distribution that produced `sequence[i+1]`.
        token_ids: list[int] = []
        byte_probs: list[float] = []

        for step, step_logits in enumerate(scores):
            tok = int(sequence[step + 1].item())
            if tok == self.tokenizer.eos_token_id:
                break
            if tok == self.tokenizer.pad_token_id:
                continue
            # Probability the model assigned to the byte it actually emitted
            step_softmax = torch.softmax(step_logits[0], dim=-1)
            byte_prob = float(step_softmax[tok].item())
            token_ids.append(tok)
            byte_probs.append(byte_prob)

        # Convert byte tokens -> raw byte values (skipping special / out-of-range)
        raw_bytes = bytearray()
        kept_probs: list[float] = []
        for tok, prob in zip(token_ids, byte_probs):
            if tok in _BYT5_BYTE_RANGE:
                raw_bytes.append(tok - _BYT5_OFFSET)
                kept_probs.append(prob)

        # UTF-8 decode the byte stream into a string. errors='replace' guards
        # against the rare case the model emits invalid byte sequences.
        decoded = bytes(raw_bytes).decode("utf-8", errors="replace")

        # Walk decoded characters and consume their byte-prob slices.
        char_probs: list[float] = []
        byte_cursor = 0
        for ch in decoded:
            if ch == "\ufffd":
                # Decoder produced a replacement char for malformed bytes.
                # Best-effort: consume one prob, mark this position low-confidence.
                char_probs.append(kept_probs[byte_cursor] if byte_cursor < len(kept_probs) else 0.0)
                byte_cursor = min(byte_cursor + 1, len(kept_probs))
                continue
            n_bytes = len(ch.encode("utf-8"))
            slice_end = min(byte_cursor + n_bytes, len(kept_probs))
            prob = 1.0
            for k in range(byte_cursor, slice_end):
                prob *= kept_probs[k]
            char_probs.append(prob)
            byte_cursor = slice_end

        # Sanity: char_probs and decoded must be the same length
        if len(char_probs) != len(decoded):
            # Fallback to overall mean for any mismatch (shouldn't happen with
            # well-formed model output, but be defensive)
            mean_p = float(sum(kept_probs) / len(kept_probs)) if kept_probs else 1.0
            char_probs = [mean_p] * len(decoded)

        return decoded, char_probs

    @staticmethod
    def _diff_positions(original: str, restored: str) -> list[int]:
        """Character positions in `restored` that differ from `original`."""
        if len(original) == len(restored):
            return [i for i, (a, b) in enumerate(zip(original, restored)) if a != b]
        return DiacriticsRestorer._diff_positions_align(original, restored)

    @staticmethod
    def _diff_positions_align(original: str, restored: str) -> list[int]:
        m, n = len(original), len(restored)
        dp = [[0] * (n + 1) for _ in range(m + 1)]
        for i in range(m + 1):
            dp[i][0] = i
        for j in range(n + 1):
            dp[0][j] = j
        for i in range(1, m + 1):
            for j in range(1, n + 1):
                if original[i - 1] == restored[j - 1]:
                    dp[i][j] = dp[i - 1][j - 1]
                else:
                    dp[i][j] = 1 + min(
                        dp[i - 1][j], dp[i][j - 1], dp[i - 1][j - 1]
                    )

        changed: list[int] = []
        i, j = m, n
        while i > 0 and j > 0:
            if original[i - 1] == restored[j - 1]:
                i -= 1
                j -= 1
            elif dp[i][j] == dp[i - 1][j - 1] + 1:   # substitution
                changed.append(j - 1)
                i -= 1
                j -= 1
            elif dp[i][j] == dp[i][j - 1] + 1:       # insertion into restored
                changed.append(j - 1)
                j -= 1
            else:                                     # deletion from original
                i -= 1
        while j > 0:
            changed.append(j - 1)
            j -= 1
        return sorted(changed)